# @name Add customers
POST http://localhost:8080/api/v1/view/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODg4MjU3MjUsImlhdCI6MTY4ODgyNDgyNSwicm9sZV9pZCI6Mn0.N1rbf_0IjbI5db7PfC0Pn7LcBzmgYYgyeUXfh5DbkQE

###
# @name Get customers
GET http://localhost:8080/api/v1/view/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODg4MjU3MjUsImlhdCI6MTY4ODgyNDgyNSwicm9sZV9pZCI6Mn0.N1rbf_0IjbI5db7PfC0Pn7LcBzmgYYgyeUXfh5DbkQE

###
# @name Update customers
PATCH http://localhost:8080/api/v1/view/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODg4MjQ5MzYsImlhdCI6MTY4ODgyNDAzNiwicm9sZV9pZCI6Mn0.p8Qa6xL24ojoe9dZsVpPzG2KVNp-3ssQIMt3iiZFFxk

###
# @name Delete customers
DELETE http://localhost:8080/api/v1/view/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODg4MjU3MjUsImlhdCI6MTY4ODgyNDgyNSwicm9sZV9pZCI6Mn0.N1rbf_0IjbI5db7PfC0Pn7LcBzmgYYgyeUXfh5DbkQE
